# Generated by Django 5.0.1 on 2024-02-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GaiaAuth", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
    ]
