# Generated by Django 5.0.1 on 2024-02-11 17:44

import GaiaAuth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GaiaAuth", "0002_remove_user_groups_remove_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingActivation",
            fields=[
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.CharField(
                        default=GaiaAuth.models.PendingActivation.generate_token, max_length=255, unique=True
                    ),
                ),
            ],
        ),
    ]
