# Generated by Django 5.0.1 on 2024-02-12 00:24

import GaiaAuth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GaiaAuth", "0003_pendingactivation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasswordReset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "token",
                    models.CharField(
                        default=GaiaAuth.models.PendingActivation.generate_token, max_length=255, unique=True
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
